export const ROLE_ACCESS: Record<string, string[]> = {
  super_admin: [
    "/dashboard",
    "/dashboard/construction",
    "/dashboard/workforce",
    "/dashboard/materials",
    "/dashboard/evidence",
    "/dashboard/ai",
    "/dashboard/audit",
    "/dashboard/finance",
    "/dashboard/import",
    "/dashboard/pos",
    "/dashboard/crm",
    "/dashboard/contractor",
    "/dashboard/inventory",
    "/dashboard/construction/projects",
    "/dashboard/reports",
    "/dashboard/settings",
  ],
  admin: [
    "/dashboard",
    "/dashboard/construction",
    "/dashboard/workforce",
    "/dashboard/materials",
    "/dashboard/evidence",
    "/dashboard/ai",
    "/dashboard/audit",
    "/dashboard/finance",
    "/dashboard/import",
    "/dashboard/pos",
    "/dashboard/crm",
    "/dashboard/contractor",
    "/dashboard/inventory",
    "/dashboard/construction/projects",
    "/dashboard/reports",
    "/dashboard/settings",
  ],
  maker: [
    "/dashboard",
    "/dashboard/construction",
    "/dashboard/workforce",
    "/dashboard/materials",
    "/dashboard/evidence",
    "/dashboard/ai",
    "/dashboard/finance",
    "/dashboard/import",
    "/dashboard/pos",
    "/dashboard/crm",
    "/dashboard/contractor",
    "/dashboard/inventory",
    "/dashboard/construction/projects",
    "/dashboard/reports",
    "/dashboard/settings",
  ],
  checker: [
    "/dashboard",
    "/dashboard/construction",
    "/dashboard/workforce",
    "/dashboard/materials",
    "/dashboard/evidence",
    "/dashboard/ai",
    "/dashboard/audit",
    "/dashboard/finance",
    "/dashboard/import",
    "/dashboard/pos",
    "/dashboard/crm",
    "/dashboard/contractor",
    "/dashboard/inventory",
    "/dashboard/construction/projects",
    "/dashboard/reports",
    "/dashboard/settings",
  ],
  viewer: [
    "/dashboard",
    "/dashboard/construction",
    "/dashboard/workforce",
    "/dashboard/materials",
    "/dashboard/evidence",
    "/dashboard/ai",
    "/dashboard/import",
    "/dashboard/pos",
    "/dashboard/crm",
    "/dashboard/contractor",
    "/dashboard/inventory",
    "/dashboard/construction/projects",
    "/dashboard/reports",
    "/dashboard/settings",
  ],
  worker: [
    "/dashboard",
    "/dashboard/construction",
    "/dashboard/workforce",
    "/dashboard/materials",
    "/dashboard/evidence",
    "/dashboard/ai",
    "/dashboard/pos",
    "/dashboard/construction/projects",
    "/dashboard/settings",
  ],
};

export function normalizeRoleName(role: string | null | undefined): string {
  return (role || "viewer").trim().toLowerCase();
}
