export const ROLE_ACCESS: Record<string, string[]> = {
  super_admin: [
    "/dashboard",
    "/dashboard/docs",
    "/dashboard/construction",
    "/dashboard/workforce",
    "/dashboard/materials",
    "/dashboard/evidence",
    "/dashboard/audit",
    "/dashboard/ai",
    "/dashboard/finance",
    "/dashboard/contractor",
    "/dashboard/construction/projects",
    "/dashboard/reports",
    "/dashboard/settings",
  ],
  admin: [
    "/dashboard",
    "/dashboard/docs",
    "/dashboard/construction",
    "/dashboard/workforce",
    "/dashboard/materials",
    "/dashboard/evidence",
    "/dashboard/audit",
    "/dashboard/ai",
    "/dashboard/finance",
    "/dashboard/contractor",
    "/dashboard/construction/projects",
    "/dashboard/reports",
    "/dashboard/settings",
  ],
  supervisor: [
    "/dashboard",
    "/dashboard/docs",
    "/dashboard/construction",
    "/dashboard/workforce",
    "/dashboard/materials",
    "/dashboard/evidence",
    "/dashboard/audit",
    "/dashboard/ai",
    "/dashboard/finance",
    "/dashboard/contractor",
    "/dashboard/construction/projects",
    "/dashboard/reports",
    "/dashboard/settings",
  ],
  engineer: [
    "/dashboard",
    "/dashboard/docs",
    "/dashboard/construction",
    "/dashboard/workforce",
    "/dashboard/materials",
    "/dashboard/evidence",
    "/dashboard/ai",
    "/dashboard/finance",
    "/dashboard/contractor",
    "/dashboard/construction/projects",
    "/dashboard/reports",
    "/dashboard/settings",
  ],
  maker: [
    "/dashboard",
    "/dashboard/docs",
    "/dashboard/construction",
    "/dashboard/workforce",
    "/dashboard/materials",
    "/dashboard/evidence",
    "/dashboard/ai",
    "/dashboard/finance",
    "/dashboard/contractor",
    "/dashboard/construction/projects",
    "/dashboard/reports",
    "/dashboard/settings",
  ],
  checker: [
    "/dashboard",
    "/dashboard/docs",
    "/dashboard/construction",
    "/dashboard/workforce",
    "/dashboard/materials",
    "/dashboard/evidence",
    "/dashboard/audit",
    "/dashboard/ai",
    "/dashboard/finance",
    "/dashboard/contractor",
    "/dashboard/construction/projects",
    "/dashboard/reports",
    "/dashboard/settings",
  ],
  viewer: [
    "/dashboard",
    "/dashboard/docs",
    "/dashboard/construction",
    "/dashboard/workforce",
    "/dashboard/materials",
    "/dashboard/evidence",
    "/dashboard/finance",
    "/dashboard/contractor",
    "/dashboard/construction/projects",
    "/dashboard/reports",
    "/dashboard/settings",
  ],
  worker: [
    "/dashboard",
    "/dashboard/docs",
    "/dashboard/construction",
    "/dashboard/workforce",
    "/dashboard/materials",
    "/dashboard/evidence",
    "/dashboard/finance",
    "/dashboard/construction/projects",
    "/dashboard/settings",
  ],
};

export function normalizeRoleName(role: string | null | undefined): string {
  const normalized = (role || "viewer")
    .trim()
    .toLowerCase()
    .replace(/[\s-]+/g, "_")
    .replace(/[^a-z_]/g, "");

  const aliases: Record<string, string> = {
    superadmin: "super_admin",
    super_admin: "super_admin",
    admin: "admin",
    supervisor: "supervisor",
    engineer: "engineer",
    maker: "maker",
    checker: "checker",
    viewer: "viewer",
    worker: "worker",
  };

  return aliases[normalized] ?? "viewer";
}
